### ISSUE TITLE
Wrong system bars color, it is needed to be transparent

### ISSUE THREAD

**Issue by T8RIN** [kaajjo/Libre-Sudoku#17]
remove this line please 
systemUiController.setSystemBarsColor(MaterialTheme.colorScheme.surface)

**Comment by kaajjo** [comment]
Why? Is there any significant reason? Because if it's set to transparent, it looks bad and out of place. Am I missing something?
Transparent bar
<img src="https://user-images.githubusercontent.com/87094439/213115592-f92e0d49-593c-437e-821f-facf467f1053.png" width=50% height=50%>

With surface color
<img src="https://user-images.githubusercontent.com/87094439/213115598-1eaa8824-29b5-4445-9e21-9378a0998108.png" width=50% height=50%>

**Comment by T8RIN** [comment]
> Why? Is there any significant reason? Because if it's set to transparent, it looks bad and out of place. Am I missing something? Transparent bar <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/87094439/213115592-f92e0d49-593c-437e-821f-facf467f1053.png">
> 
> With surface color <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/87094439/213115598-1eaa8824-29b5-4445-9e21-9378a0998108.png">

You need to use window insets to make it better, you can see how i implemented it in my CookHelper app https://github.com/t8rin/cookhelper

**Comment by T8RIN** [comment]
> Why? Is there any significant reason? Because if it's set to transparent, it looks bad and out of place. Am I missing something?
> Transparent bar
> <img src="https://user-images.githubusercontent.com/87094439/213115592-f92e0d49-593c-437e-821f-facf467f1053.png" width=50% height=50%>
> 
> With surface color
> <img src="https://user-images.githubusercontent.com/87094439/213115598-1eaa8824-29b5-4445-9e21-9378a0998108.png" width=50% height=50%>
> 

Also see "Jetpack Compose edge-to-edge

**Comment by kaajjo** [comment]
Ok, thanks. I think I got it
