### ISSUE TITLE
Unsolvable Sudoku

### ISSUE THREAD

**Issue by and4po** [kaajjo/Libre-Sudoku#74]
I was playing a game when I found that it was impossible to solve.
As you can see below, I was playing at the easy mode.
I'm using Android 10, if it helps.
I still have the game open, so if you need some log or something, just let me know.
![photo_2023-09-28_18-32-01](https://github.com/kaajjo/Libre-Sudoku/assets/94716615/16974ec0-8469-4906-9638-125f913534af)
![photo_2023-09-28_18-32-04](https://github.com/kaajjo/Libre-Sudoku/assets/94716615/96cbfbc0-57d3-431c-8543-fb775ca69d3b)
Thank you!

**Comment by kaajjo** [comment]
Hi, it looks like you made a mistake when solving this sudoku. I just checked it with other online solvers and this sudoku has 1 solution.
Remember that there are 2 options for app to check for mistakes:
1. According to the rules of sudoku. It will mark a number as a mistake only when it breaks the rules (e.g. same numbers in one row/column etc.). But if a number is not marked as a mistake, it doesn't mean that in the solution that number will be there. It means that there are no errors _at the moment_.
2. Comparison with the final solution. It will mark a cell as a mistake when it contains a number different from the one in the solution.
In the first case, it is quite possible that you may make a mistake that will eventually lead you to a dead end. That's how sudoku works. Only enter a number if you can prove that it must go here (but of course, we all make mistakes).
However, many people may find it too hard or confusing, which is why there is a second option.

**Comment by kaajjo** [comment]
Here's what the solution looks like
<img src="https://github.com/kaajjo/Libre-Sudoku/assets/87094439/b646a283-c4a2-4f39-b4ee-5bb3247a2a14" width=50%>

**Comment by and4po** [comment]
Oh, yeah, I'm sorry. I didn't think about that, I thought that the default checker checks with the answer, but it makes more sense like this for default. Thank you really much for the answer!

PD: On propuse, are you planning to release a new version soon?
(Just asking to know if I have to finish the translation soon)

**Comment by kaajjo** [comment]
> PD: On propuse, are you planning to release a new version soon?

Yes, I'm currently working on backup/restore games and settings, and statistics export. Probably next week or a little later
